# general settings
name: 001_ESRGAN_x4_FIE
model_type: ESRGANModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: FoundationHist
    type: PairedImageDataset
    dataroot_gt: /project/kimlab_tcga/AdaSlide_dataset/HR/train
    dataroot_lq: /project/kimlab_tcga/AdaSlide_dataset/LR-x4/train
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 24
    batch_size_per_gpu: 384
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: FoundationHist
    type: PairedImageDataset
    dataroot_gt: /project/kimlab_tcga/AdaSlide_dataset/HR/valid
    dataroot_lq: /project/kimlab_tcga/AdaSlide_dataset/LR-x4/valid
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_g: experiments/pretrained_models/ESRGAN_SRx4.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: 10000
  # warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: PathoSR
    resume_id: 

# dist training settings
dist_params:
  backend: nccl
  port: 29500
